key:
  location:
    private: "file:${user.home}/.key/zoostar.key"
    public: "file:${user.home}/.key/zoostar.cer"
server:
  forward-headers-strategy: NATIVE
  tomcat:
    redirect-context-root: false