spring:
  security:
    saml2:
      relyingparty:
        registration:
          google:
            identityprovider:
              entity-id: net-zoostar-hello-world-saml
              metadata-uri: "classpath:metadata/GoogleIDPMetadata.xml"
