spring:
  profiles:
    active:
      - local

spring:
  security:
    saml2:
      relyingparty:
        registration:
          google:
            identityprovider:
              metadata-uri: "classpath:metadata/GoogleIDPMetadata.xml"
