spring:
  security:
    enabled: true
    saml2:
      relyingparty:
        registration:
          google:
            acs:
              location: ${acs.url}
            signing:
              credentials:
                - private-key-location: ${key.location.private}
                  certificate-location: ${key.location.public}
            identityprovider:
              metadata-uri: "classpath:metadata/GoogleIDPMetadata.xml"
